// Mocks generated by Mockito from annotations
// in ddapp_mobile/test/unit/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;

import 'package:ddapp_mobile/data/api/api_client.dart' as _i4;
import 'package:dio/dio.dart' as _i2;
import 'package:flutter/foundation.dart' as _i6;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_1 extends _i1.SmartFake implements _i3.IOSOptions {
  _FakeIOSOptions_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_2 extends _i1.SmartFake
    implements _i3.AndroidOptions {
  _FakeAndroidOptions_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_3 extends _i1.SmartFake implements _i3.LinuxOptions {
  _FakeLinuxOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_4 extends _i1.SmartFake
    implements _i3.WindowsOptions {
  _FakeWindowsOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_5 extends _i1.SmartFake implements _i3.WebOptions {
  _FakeWebOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppleOptions_6 extends _i1.SmartFake implements _i3.AppleOptions {
  _FakeAppleOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSecureStorageUpgradeStatus_7 extends _i1.SmartFake
    implements _i3.SecureStorageUpgradeStatus {
  _FakeSecureStorageUpgradeStatus_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) => (super.noSuchMethod(
    Invocation.method(
      #get,
      [path],
      {#queryParameters: queryParameters, #options: options},
    ),
    returnValue: _i5.Future<_i2.Response<dynamic>>.value(
      _FakeResponse_0<dynamic>(
        this,
        Invocation.method(
          #get,
          [path],
          {#queryParameters: queryParameters, #options: options},
        ),
      ),
    ),
  ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> post(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) => (super.noSuchMethod(
    Invocation.method(
      #post,
      [path],
      {#data: data, #queryParameters: queryParameters, #options: options},
    ),
    returnValue: _i5.Future<_i2.Response<dynamic>>.value(
      _FakeResponse_0<dynamic>(
        this,
        Invocation.method(
          #post,
          [path],
          {#data: data, #queryParameters: queryParameters, #options: options},
        ),
      ),
    ),
  ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> put(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) => (super.noSuchMethod(
    Invocation.method(
      #put,
      [path],
      {#data: data, #queryParameters: queryParameters, #options: options},
    ),
    returnValue: _i5.Future<_i2.Response<dynamic>>.value(
      _FakeResponse_0<dynamic>(
        this,
        Invocation.method(
          #put,
          [path],
          {#data: data, #queryParameters: queryParameters, #options: options},
        ),
      ),
    ),
  ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> delete(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) => (super.noSuchMethod(
    Invocation.method(
      #delete,
      [path],
      {#data: data, #queryParameters: queryParameters, #options: options},
    ),
    returnValue: _i5.Future<_i2.Response<dynamic>>.value(
      _FakeResponse_0<dynamic>(
        this,
        Invocation.method(
          #delete,
          [path],
          {#data: data, #queryParameters: queryParameters, #options: options},
        ),
      ),
    ),
  ) as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> uploadFile(
    String? path,
    String? filePath, {
    Map<String, dynamic>? data,
    _i2.ProgressCallback? onSendProgress,
  }) => (super.noSuchMethod(
    Invocation.method(
      #uploadFile,
      [path, filePath],
      {#data: data, #onSendProgress: onSendProgress},
    ),
    returnValue: _i5.Future<_i2.Response<dynamic>>.value(
      _FakeResponse_0<dynamic>(
        this,
        Invocation.method(
          #uploadFile,
          [path, filePath],
          {#data: data, #onSendProgress: onSendProgress},
        ),
      ),
    ),
  ) as _i5.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i3.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IOSOptions get iOptions => (super.noSuchMethod(
    Invocation.getter(#iOptions),
    returnValue: _FakeIOSOptions_1(this, Invocation.getter(#iOptions)),
  ) as _i3.IOSOptions);

  @override
  _i3.AndroidOptions get aOptions => (super.noSuchMethod(
    Invocation.getter(#aOptions),
    returnValue: _FakeAndroidOptions_2(this, Invocation.getter(#aOptions)),
  ) as _i3.AndroidOptions);

  @override
  _i3.LinuxOptions get lOptions => (super.noSuchMethod(
    Invocation.getter(#lOptions),
    returnValue: _FakeLinuxOptions_3(this, Invocation.getter(#lOptions)),
  ) as _i3.LinuxOptions);

  @override
  _i3.WindowsOptions get wOptions => (super.noSuchMethod(
    Invocation.getter(#wOptions),
    returnValue: _FakeWindowsOptions_4(this, Invocation.getter(#wOptions)),
  ) as _i3.WindowsOptions);

  @override
  _i3.WebOptions get webOptions => (super.noSuchMethod(
    Invocation.getter(#webOptions),
    returnValue: _FakeWebOptions_5(this, Invocation.getter(#webOptions)),
  ) as _i3.WebOptions);

  @override
  _i3.AppleOptions get mOptions => (super.noSuchMethod(
    Invocation.getter(#mOptions),
    returnValue: _FakeAppleOptions_6(this, Invocation.getter(#mOptions)),
  ) as _i3.AppleOptions);

  @override
  Map<String, List<_i6.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
        Invocation.getter(#getListeners),
        returnValue: <String, List<_i6.ValueChanged<String?>>>{},
      ) as Map<String, List<_i6.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i6.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i6.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> write({
    required String? key,
    required String? value,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) => (super.noSuchMethod(
    Invocation.method(#write, [], {
      #key: key,
      #value: value,
      #iOptions: iOptions,
      #aOptions: aOptions,
      #lOptions: lOptions,
      #webOptions: webOptions,
      #mOptions: mOptions,
      #wOptions: wOptions,
    }),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<String?> read({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) => (super.noSuchMethod(
    Invocation.method(#read, [], {
      #key: key,
      #iOptions: iOptions,
      #aOptions: aOptions,
      #lOptions: lOptions,
      #webOptions: webOptions,
      #mOptions: mOptions,
      #wOptions: wOptions,
    }),
    returnValue: _i5.Future<String?>.value(),
  ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> containsKey({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) => (super.noSuchMethod(
    Invocation.method(#containsKey, [], {
      #key: key,
      #iOptions: iOptions,
      #aOptions: aOptions,
      #lOptions: lOptions,
      #webOptions: webOptions,
      #mOptions: mOptions,
      #wOptions: wOptions,
    }),
    returnValue: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> delete({
    required String? key,
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) => (super.noSuchMethod(
    Invocation.method(#delete, [], {
      #key: key,
      #iOptions: iOptions,
      #aOptions: aOptions,
      #lOptions: lOptions,
      #webOptions: webOptions,
      #mOptions: mOptions,
      #wOptions: wOptions,
    }),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, String>> readAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) => (super.noSuchMethod(
    Invocation.method(#readAll, [], {
      #iOptions: iOptions,
      #aOptions: aOptions,
      #lOptions: lOptions,
      #webOptions: webOptions,
      #mOptions: mOptions,
      #wOptions: wOptions,
    }),
    returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
  ) as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<void> deleteAll({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) => (super.noSuchMethod(
    Invocation.method(#deleteAll, [], {
      #iOptions: iOptions,
      #aOptions: aOptions,
      #lOptions: lOptions,
      #webOptions: webOptions,
      #mOptions: mOptions,
      #wOptions: wOptions,
    }),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
    Invocation.method(#isCupertinoProtectedDataAvailable, []),
    returnValue: _i5.Future<bool?>.value(),
  ) as _i5.Future<bool?>);

  @override
  _i5.Future<_i3.SecureStorageUpgradeStatus> checkUpgradeStatus({
    _i3.AppleOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.AppleOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) => (super.noSuchMethod(
    Invocation.method(#checkUpgradeStatus, [], {
      #iOptions: iOptions,
      #aOptions: aOptions,
      #lOptions: lOptions,
      #webOptions: webOptions,
      #mOptions: mOptions,
      #wOptions: wOptions,
    }),
    returnValue: _i5.Future<_i3.SecureStorageUpgradeStatus>.value(
      _FakeSecureStorageUpgradeStatus_7(
        this,
        Invocation.method(#checkUpgradeStatus, [], {
          #iOptions: iOptions,
          #aOptions: aOptions,
          #lOptions: lOptions,
          #webOptions: webOptions,
          #mOptions: mOptions,
          #wOptions: wOptions,
        }),
      ),
    ),
  ) as _i5.Future<_i3.SecureStorageUpgradeStatus>);
}
