// Mocks generated by Mockito from annotations
// in ddapp_mobile/test/unit/dashboard_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:ddapp_mobile/data/models/api_response.dart' as _i2;
import 'package:ddapp_mobile/data/models/dashboard.dart' as _i5;
import 'package:ddapp_mobile/data/repositories/dashboard_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardRepository extends _i1.Mock
    implements _i3.DashboardRepository {
  MockDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.DashboardData>> getDashboardData({
    String? period = 'this-month',
  }) => (super.noSuchMethod(
    Invocation.method(#getDashboardData, [], {#period: period}),
    returnValue: _i4.Future<_i2.ApiResponse<_i5.DashboardData>>.value(
      _FakeApiResponse_0<_i5.DashboardData>(
        this,
        Invocation.method(#getDashboardData, [], {#period: period}),
      ),
    ),
  ) as _i4.Future<_i2.ApiResponse<_i5.DashboardData>>);
}
