// Mocks generated by Mockito from annotations
// in ddapp_mobile/test/unit/expense_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:ddapp_mobile/data/models/api_response.dart' as _i2;
import 'package:ddapp_mobile/data/models/expense.dart' as _i5;
import 'package:ddapp_mobile/data/repositories/expense_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i3.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Expense>>> getExpenses({
    String? status,
    int? limit,
    int? offset,
  }) => (super.noSuchMethod(
    Invocation.method(#getExpenses, [], {
      #status: status,
      #limit: limit,
      #offset: offset,
    }),
    returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Expense>>>.value(
      _FakeApiResponse_0<List<_i5.Expense>>(
        this,
        Invocation.method(#getExpenses, [], {
          #status: status,
          #limit: limit,
          #offset: offset,
        }),
      ),
    ),
  ) as _i4.Future<_i2.ApiResponse<List<_i5.Expense>>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Expense>> getExpense(String? id) =>
      (super.noSuchMethod(
        Invocation.method(#getExpense, [id]),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.Expense>>.value(
          _FakeApiResponse_0<_i5.Expense>(
            this,
            Invocation.method(#getExpense, [id]),
          ),
        ),
      ) as _i4.Future<_i2.ApiResponse<_i5.Expense>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Expense>> createExpense(
    _i5.CreateExpenseRequest? request,
  ) => (super.noSuchMethod(
    Invocation.method(#createExpense, [request]),
    returnValue: _i4.Future<_i2.ApiResponse<_i5.Expense>>.value(
      _FakeApiResponse_0<_i5.Expense>(
        this,
        Invocation.method(#createExpense, [request]),
      ),
    ),
  ) as _i4.Future<_i2.ApiResponse<_i5.Expense>>);

  @override
  _i4.Future<_i2.ApiResponse<String>> uploadReceipt(
    String? expenseId,
    String? filePath, {
    dynamic Function(int, int)? onProgress,
  }) => (super.noSuchMethod(
    Invocation.method(
      #uploadReceipt,
      [expenseId, filePath],
      {#onProgress: onProgress},
    ),
    returnValue: _i4.Future<_i2.ApiResponse<String>>.value(
      _FakeApiResponse_0<String>(
        this,
        Invocation.method(
          #uploadReceipt,
          [expenseId, filePath],
          {#onProgress: onProgress},
        ),
      ),
    ),
  ) as _i4.Future<_i2.ApiResponse<String>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Expense>> approveExpense(
    String? id, {
    String? approvalType = 'recorded',
  }) => (super.noSuchMethod(
    Invocation.method(#approveExpense, [id], {#approvalType: approvalType}),
    returnValue: _i4.Future<_i2.ApiResponse<_i5.Expense>>.value(
      _FakeApiResponse_0<_i5.Expense>(
        this,
        Invocation.method(#approveExpense, [id], {#approvalType: approvalType}),
      ),
    ),
  ) as _i4.Future<_i2.ApiResponse<_i5.Expense>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Expense>> rejectExpense(
    String? id, {
    String? reason,
  }) => (super.noSuchMethod(
    Invocation.method(#rejectExpense, [id], {#reason: reason}),
    returnValue: _i4.Future<_i2.ApiResponse<_i5.Expense>>.value(
      _FakeApiResponse_0<_i5.Expense>(
        this,
        Invocation.method(#rejectExpense, [id], {#reason: reason}),
      ),
    ),
  ) as _i4.Future<_i2.ApiResponse<_i5.Expense>>);
}
